---
- hosts: server2
  become: yes
  remote_user: mariana
  tasks:
  - name: Instalando o Nginx
    apt: 
      name: nginx
      state: latest
      update_cache: yes

  - name: Habilitando o start do Nginx no boot
    service:
      name: nginx
      enabled: yes    

  - name: Iniciando o Nginx  
    service: 
       name: nginx
       state: started

  - name: Copiando html personalizado
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Copiando nginx.conf
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Restartando o Nginx

  handlers:
  - name: Restartando o Nginx
    service:
      name: nginx
      state: restarted    
